### ISSUE TITLE
Get chat ID to send a message

### ISSUE THREAD

**Issue by kratatomi** [J-Rios/uTLGBotLib-arduino#4]
Hi, I'm trying to use your library in my project and at the moment is the best one I've tried. In the examples I see that the bot works forever in a while loop, but there's any way to get the chat id and just send a message? I don't intent to receive any msg in my project.

**Comment by J-Rios** [comment]
Hi,

This is a question related to Telegram Bot API usage and it applies to all libraries for any platform and programming language.

To send a Telegram message to a chat (private chat, group or channel) the Bot needs to know an "address" to that chat, that is the chat ID.

Any message received by the Bot has the chat ID value from where it comes, that is why in the examples (like "echo" one), when the Bot receive a message it response sending a message to received chat ID, that allows the Bot to response to any chat that talk to him.

If you want to send a message to a chat without receiving messages from it, you must known the chat ID before, and place it into your sketch like a constant value. Something that some users do is get their user ID (because user ID is equal to private chat ID of that user) and place it as constant to makes Bot only works for messages coming from that user (owner of the bot) and nobody else.

You can get chats IDs by using example "show_received_messages" first and then use them in your sketchs.

Also, note that some Telegram rule say that Bot can't send message to a user (private chat) if it has not send a message to the Bot first.

Regards.

**Comment by kratatomi** [comment]
Hi, thank you for your answer, very informative. 
I found that one way to get the ID is to call periodically Bot.getUpdates() until I get the ID stored in Bot.received_msg.chat.id, then I can send messages with no issues. 
My doubt is what condition use to know that Bot.received_msg.chat.id has/has not the ID stored. I tried with 
`if (Bot.received_msg.chat.id == NULL )` with no success...

**Comment by J-Rios** [comment]
Received message chat ID is an array of chars and it is initialized to be empty, so it should be:

`if(Bot.received_msg.chat.id[0] == '\0')`

**Comment by kratatomi** [comment]
Thank you, it works!
